package bg.sofia.uni.fmi.mjt.sentiment;

public class StopWordSampleData {
    private static final String STOP_WORDS =
            "a" + System.lineSeparator() +
                    "about" + System.lineSeparator() +
                    "above" + System.lineSeparator() +
                    "after" + System.lineSeparator() +
                    "again" + System.lineSeparator() +
                    "against" + System.lineSeparator() +
                    "all" + System.lineSeparator() +
                    "am" + System.lineSeparator() +
                    "an" + System.lineSeparator() +
                    "and" + System.lineSeparator() +
                    "any" + System.lineSeparator() +
                    "are" + System.lineSeparator() +
                    "aren't" + System.lineSeparator() +
                    "as" + System.lineSeparator() +
                    "at" + System.lineSeparator() +
                    "be" + System.lineSeparator() +
                    "because" + System.lineSeparator() +
                    "been" + System.lineSeparator() +
                    "before" + System.lineSeparator() +
                    "being" + System.lineSeparator() +
                    "below" + System.lineSeparator() +
                    "between" + System.lineSeparator() +
                    "both" + System.lineSeparator() +
                    "but" + System.lineSeparator() +
                    "by" + System.lineSeparator() +
                    "can't" + System.lineSeparator() +
                    "cannot" + System.lineSeparator() +
                    "could" + System.lineSeparator() +
                    "couldn't" + System.lineSeparator() +
                    "did" + System.lineSeparator() +
                    "didn't" + System.lineSeparator() +
                    "do" + System.lineSeparator() +
                    "does" + System.lineSeparator() +
                    "doesn't" + System.lineSeparator() +
                    "doing" + System.lineSeparator() +
                    "don't" + System.lineSeparator() +
                    "down" + System.lineSeparator() +
                    "during" + System.lineSeparator() +
                    "each" + System.lineSeparator() +
                    "few" + System.lineSeparator() +
                    "for" + System.lineSeparator() +
                    "from" + System.lineSeparator() +
                    "further" + System.lineSeparator() +
                    "had" + System.lineSeparator() +
                    "hadn't" + System.lineSeparator() +
                    "has" + System.lineSeparator() +
                    "hasn't" + System.lineSeparator() +
                    "have" + System.lineSeparator() +
                    "haven't" + System.lineSeparator() +
                    "having" + System.lineSeparator() +
                    "he" + System.lineSeparator() +
                    "he'd" + System.lineSeparator() +
                    "he'll" + System.lineSeparator() +
                    "he's" + System.lineSeparator() +
                    "her" + System.lineSeparator() +
                    "here" + System.lineSeparator() +
                    "here's" + System.lineSeparator() +
                    "hers" + System.lineSeparator() +
                    "herself" + System.lineSeparator() +
                    "him" + System.lineSeparator() +
                    "himself" + System.lineSeparator() +
                    "his" + System.lineSeparator() +
                    "how" + System.lineSeparator() +
                    "how's" + System.lineSeparator() +
                    "i" + System.lineSeparator() +
                    "i'd" + System.lineSeparator() +
                    "i'll" + System.lineSeparator() +
                    "i'm" + System.lineSeparator() +
                    "i've" + System.lineSeparator() +
                    "if" + System.lineSeparator() +
                    "in" + System.lineSeparator() +
                    "into" + System.lineSeparator() +
                    "is" + System.lineSeparator() +
                    "isn't" + System.lineSeparator() +
                    "it" + System.lineSeparator() +
                    "it's" + System.lineSeparator() +
                    "its" + System.lineSeparator() +
                    "itself" + System.lineSeparator() +
                    "let's" + System.lineSeparator() +
                    "me" + System.lineSeparator() +
                    "more" + System.lineSeparator() +
                    "most" + System.lineSeparator() +
                    "mustn't" + System.lineSeparator() +
                    "my" + System.lineSeparator() +
                    "myself" + System.lineSeparator() +
                    "no" + System.lineSeparator() +
                    "nor" + System.lineSeparator() +
                    "not" + System.lineSeparator() +
                    "of" + System.lineSeparator() +
                    "off" + System.lineSeparator() +
                    "on" + System.lineSeparator() +
                    "once" + System.lineSeparator() +
                    "only" + System.lineSeparator() +
                    "or" + System.lineSeparator() +
                    "other" + System.lineSeparator() +
                    "ought" + System.lineSeparator() +
                    "our" + System.lineSeparator() +
                    "ours" + System.lineSeparator() +
                    "ourselves" + System.lineSeparator() +
                    "out" + System.lineSeparator() +
                    "over" + System.lineSeparator() +
                    "own" + System.lineSeparator() +
                    "same" + System.lineSeparator() +
                    "shan't" + System.lineSeparator() +
                    "she" + System.lineSeparator() +
                    "she'd" + System.lineSeparator() +
                    "she'll" + System.lineSeparator() +
                    "she's" + System.lineSeparator() +
                    "should" + System.lineSeparator() +
                    "shouldn't" + System.lineSeparator() +
                    "so" + System.lineSeparator() +
                    "some" + System.lineSeparator() +
                    "such" + System.lineSeparator() +
                    "than" + System.lineSeparator() +
                    "that" + System.lineSeparator() +
                    "that's" + System.lineSeparator() +
                    "the" + System.lineSeparator() +
                    "their" + System.lineSeparator() +
                    "theirs" + System.lineSeparator() +
                    "them" + System.lineSeparator() +
                    "themselves" + System.lineSeparator() +
                    "then" + System.lineSeparator() +
                    "there" + System.lineSeparator() +
                    "there's" + System.lineSeparator() +
                    "these" + System.lineSeparator() +
                    "they" + System.lineSeparator() +
                    "they'd" + System.lineSeparator() +
                    "they'll" + System.lineSeparator() +
                    "they're" + System.lineSeparator() +
                    "they've" + System.lineSeparator() +
                    "this" + System.lineSeparator() +
                    "those" + System.lineSeparator() +
                    "through" + System.lineSeparator() +
                    "to" + System.lineSeparator() +
                    "too" + System.lineSeparator() +
                    "under" + System.lineSeparator() +
                    "until" + System.lineSeparator() +
                    "up" + System.lineSeparator() +
                    "very" + System.lineSeparator() +
                    "was" + System.lineSeparator() +
                    "wasn't" + System.lineSeparator() +
                    "we" + System.lineSeparator() +
                    "we'd" + System.lineSeparator() +
                    "we'll" + System.lineSeparator() +
                    "we're" + System.lineSeparator() +
                    "we've" + System.lineSeparator() +
                    "were" + System.lineSeparator() +
                    "weren't" + System.lineSeparator() +
                    "what" + System.lineSeparator() +
                    "what's" + System.lineSeparator() +
                    "when" + System.lineSeparator() +
                    "when's" + System.lineSeparator() +
                    "where" + System.lineSeparator() +
                    "where's" + System.lineSeparator() +
                    "which" + System.lineSeparator() +
                    "while" + System.lineSeparator() +
                    "who" + System.lineSeparator() +
                    "who's" + System.lineSeparator() +
                    "whom" + System.lineSeparator() +
                    "why" + System.lineSeparator() +
                    "why's" + System.lineSeparator() +
                    "with" + System.lineSeparator() +
                    "won't" + System.lineSeparator() +
                    "would" + System.lineSeparator() +
                    "wouldn't" + System.lineSeparator() +
                    "you" + System.lineSeparator() +
                    "you'd" + System.lineSeparator() +
                    "you'll" + System.lineSeparator() +
                    "you're" + System.lineSeparator() +
                    "you've" + System.lineSeparator() +
                    "your" + System.lineSeparator() +
                    "yours" + System.lineSeparator() +
                    "yourself" + System.lineSeparator() +
                    "yourselves";

    public static String getInstance() {
        return STOP_WORDS;
    }
}
